//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoWeb.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPREmployees
    {
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public byte[] MesPassword { get; set; }
        public string AuthorityId { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<System.DateTime> GenerateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string GenerateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}
