//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoWeb01.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCMCommitStatus", Namespace="http://schemas.datacontract.org/2004/07/Mes.WcfCommonService")]
    [System.SerializableAttribute()]
    public partial class TCMCommitStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CQTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIS1_ONOFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LIS2_ONOFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_ONOFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOH_ONOFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PV8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QLPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QTNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SHIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SHI_AHEADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TLRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TSC_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TSE_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TWSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WTIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WTPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BDI {
            get {
                return this.BDIField;
            }
            set {
                if ((object.ReferenceEquals(this.BDIField, value) != true)) {
                    this.BDIField = value;
                    this.RaisePropertyChanged("BDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAV {
            get {
                return this.CAVField;
            }
            set {
                if ((object.ReferenceEquals(this.CAVField, value) != true)) {
                    this.CAVField = value;
                    this.RaisePropertyChanged("CAV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDI {
            get {
                return this.CDIField;
            }
            set {
                if ((object.ReferenceEquals(this.CDIField, value) != true)) {
                    this.CDIField = value;
                    this.RaisePropertyChanged("CDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDT {
            get {
                return this.CDTField;
            }
            set {
                if ((object.ReferenceEquals(this.CDTField, value) != true)) {
                    this.CDTField = value;
                    this.RaisePropertyChanged("CDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPR {
            get {
                return this.CPRField;
            }
            set {
                if ((object.ReferenceEquals(this.CPRField, value) != true)) {
                    this.CPRField = value;
                    this.RaisePropertyChanged("CPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPT {
            get {
                return this.CPTField;
            }
            set {
                if ((object.ReferenceEquals(this.CPTField, value) != true)) {
                    this.CPTField = value;
                    this.RaisePropertyChanged("CPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CQT {
            get {
                return this.CQTField;
            }
            set {
                if ((object.ReferenceEquals(this.CQTField, value) != true)) {
                    this.CQTField = value;
                    this.RaisePropertyChanged("CQT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTL {
            get {
                return this.CTLField;
            }
            set {
                if ((object.ReferenceEquals(this.CTLField, value) != true)) {
                    this.CTLField = value;
                    this.RaisePropertyChanged("CTL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DCD {
            get {
                return this.DCDField;
            }
            set {
                if ((object.ReferenceEquals(this.DCDField, value) != true)) {
                    this.DCDField = value;
                    this.RaisePropertyChanged("DCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DCI {
            get {
                return this.DCIField;
            }
            set {
                if ((object.ReferenceEquals(this.DCIField, value) != true)) {
                    this.DCIField = value;
                    this.RaisePropertyChanged("DCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DDI {
            get {
                return this.DDIField;
            }
            set {
                if ((object.ReferenceEquals(this.DDIField, value) != true)) {
                    this.DDIField = value;
                    this.RaisePropertyChanged("DDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DER {
            get {
                return this.DERField;
            }
            set {
                if ((object.ReferenceEquals(this.DERField, value) != true)) {
                    this.DERField = value;
                    this.RaisePropertyChanged("DER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DID {
            get {
                return this.DIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DIDField, value) != true)) {
                    this.DIDField = value;
                    this.RaisePropertyChanged("DID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNM {
            get {
                return this.DNMField;
            }
            set {
                if ((object.ReferenceEquals(this.DNMField, value) != true)) {
                    this.DNMField = value;
                    this.RaisePropertyChanged("DNM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTI {
            get {
                return this.DTIField;
            }
            set {
                if ((object.ReferenceEquals(this.DTIField, value) != true)) {
                    this.DTIField = value;
                    this.RaisePropertyChanged("DTI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTN {
            get {
                return this.DTNField;
            }
            set {
                if ((object.ReferenceEquals(this.DTNField, value) != true)) {
                    this.DTNField = value;
                    this.RaisePropertyChanged("DTN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTY {
            get {
                return this.DTYField;
            }
            set {
                if ((object.ReferenceEquals(this.DTYField, value) != true)) {
                    this.DTYField = value;
                    this.RaisePropertyChanged("DTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETS {
            get {
                return this.ETSField;
            }
            set {
                if ((object.ReferenceEquals(this.ETSField, value) != true)) {
                    this.ETSField = value;
                    this.RaisePropertyChanged("ETS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDI {
            get {
                return this.FDIField;
            }
            set {
                if ((object.ReferenceEquals(this.FDIField, value) != true)) {
                    this.FDIField = value;
                    this.RaisePropertyChanged("FDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FID {
            get {
                return this.FIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FIDField, value) != true)) {
                    this.FIDField = value;
                    this.RaisePropertyChanged("FID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FMP {
            get {
                return this.FMPField;
            }
            set {
                if ((object.ReferenceEquals(this.FMPField, value) != true)) {
                    this.FMPField = value;
                    this.RaisePropertyChanged("FMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HID {
            get {
                return this.HIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HIDField, value) != true)) {
                    this.HIDField = value;
                    this.RaisePropertyChanged("HID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDM {
            get {
                return this.IDMField;
            }
            set {
                if ((object.ReferenceEquals(this.IDMField, value) != true)) {
                    this.IDMField = value;
                    this.RaisePropertyChanged("IDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIS1_ONOFF {
            get {
                return this.LIS1_ONOFFField;
            }
            set {
                if ((object.ReferenceEquals(this.LIS1_ONOFFField, value) != true)) {
                    this.LIS1_ONOFFField = value;
                    this.RaisePropertyChanged("LIS1_ONOFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LIS2_ONOFF {
            get {
                return this.LIS2_ONOFFField;
            }
            set {
                if ((object.ReferenceEquals(this.LIS2_ONOFFField, value) != true)) {
                    this.LIS2_ONOFFField = value;
                    this.RaisePropertyChanged("LIS2_ONOFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOC {
            get {
                return this.LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCField, value) != true)) {
                    this.LOCField = value;
                    this.RaisePropertyChanged("LOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOC_ONOFF {
            get {
                return this.LOC_ONOFFField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_ONOFFField, value) != true)) {
                    this.LOC_ONOFFField = value;
                    this.RaisePropertyChanged("LOC_ONOFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOH {
            get {
                return this.LOHField;
            }
            set {
                if ((object.ReferenceEquals(this.LOHField, value) != true)) {
                    this.LOHField = value;
                    this.RaisePropertyChanged("LOH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOH_ONOFF {
            get {
                return this.LOH_ONOFFField;
            }
            set {
                if ((object.ReferenceEquals(this.LOH_ONOFFField, value) != true)) {
                    this.LOH_ONOFFField = value;
                    this.RaisePropertyChanged("LOH_ONOFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NSE {
            get {
                return this.NSEField;
            }
            set {
                if ((object.ReferenceEquals(this.NSEField, value) != true)) {
                    this.NSEField = value;
                    this.RaisePropertyChanged("NSE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NSI {
            get {
                return this.NSIField;
            }
            set {
                if ((object.ReferenceEquals(this.NSIField, value) != true)) {
                    this.NSIField = value;
                    this.RaisePropertyChanged("NSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCDF {
            get {
                return this.PCDFField;
            }
            set {
                if ((object.ReferenceEquals(this.PCDFField, value) != true)) {
                    this.PCDFField = value;
                    this.RaisePropertyChanged("PCDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCI {
            get {
                return this.PCIField;
            }
            set {
                if ((object.ReferenceEquals(this.PCIField, value) != true)) {
                    this.PCIField = value;
                    this.RaisePropertyChanged("PCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PDI {
            get {
                return this.PDIField;
            }
            set {
                if ((object.ReferenceEquals(this.PDIField, value) != true)) {
                    this.PDIField = value;
                    this.RaisePropertyChanged("PDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PID {
            get {
                return this.PIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PIDField, value) != true)) {
                    this.PIDField = value;
                    this.RaisePropertyChanged("PID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTIF {
            get {
                return this.PTIFField;
            }
            set {
                if ((object.ReferenceEquals(this.PTIFField, value) != true)) {
                    this.PTIFField = value;
                    this.RaisePropertyChanged("PTIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTQ {
            get {
                return this.PTQField;
            }
            set {
                if ((object.ReferenceEquals(this.PTQField, value) != true)) {
                    this.PTQField = value;
                    this.RaisePropertyChanged("PTQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV1 {
            get {
                return this.PV1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV1Field, value) != true)) {
                    this.PV1Field = value;
                    this.RaisePropertyChanged("PV1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV2 {
            get {
                return this.PV2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV2Field, value) != true)) {
                    this.PV2Field = value;
                    this.RaisePropertyChanged("PV2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV3 {
            get {
                return this.PV3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV3Field, value) != true)) {
                    this.PV3Field = value;
                    this.RaisePropertyChanged("PV3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV4 {
            get {
                return this.PV4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV4Field, value) != true)) {
                    this.PV4Field = value;
                    this.RaisePropertyChanged("PV4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV5 {
            get {
                return this.PV5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV5Field, value) != true)) {
                    this.PV5Field = value;
                    this.RaisePropertyChanged("PV5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV6 {
            get {
                return this.PV6Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV6Field, value) != true)) {
                    this.PV6Field = value;
                    this.RaisePropertyChanged("PV6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV7 {
            get {
                return this.PV7Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV7Field, value) != true)) {
                    this.PV7Field = value;
                    this.RaisePropertyChanged("PV7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PV8 {
            get {
                return this.PV8Field;
            }
            set {
                if ((object.ReferenceEquals(this.PV8Field, value) != true)) {
                    this.PV8Field = value;
                    this.RaisePropertyChanged("PV8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QLP {
            get {
                return this.QLPField;
            }
            set {
                if ((object.ReferenceEquals(this.QLPField, value) != true)) {
                    this.QLPField = value;
                    this.RaisePropertyChanged("QLP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QTN {
            get {
                return this.QTNField;
            }
            set {
                if ((object.ReferenceEquals(this.QTNField, value) != true)) {
                    this.QTNField = value;
                    this.RaisePropertyChanged("QTN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SCT {
            get {
                return this.SCTField;
            }
            set {
                if ((object.ReferenceEquals(this.SCTField, value) != true)) {
                    this.SCTField = value;
                    this.RaisePropertyChanged("SCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SHI {
            get {
                return this.SHIField;
            }
            set {
                if ((object.ReferenceEquals(this.SHIField, value) != true)) {
                    this.SHIField = value;
                    this.RaisePropertyChanged("SHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SHI_AHEAD {
            get {
                return this.SHI_AHEADField;
            }
            set {
                if ((object.ReferenceEquals(this.SHI_AHEADField, value) != true)) {
                    this.SHI_AHEADField = value;
                    this.RaisePropertyChanged("SHI_AHEAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLP {
            get {
                return this.SLPField;
            }
            set {
                if ((object.ReferenceEquals(this.SLPField, value) != true)) {
                    this.SLPField = value;
                    this.RaisePropertyChanged("SLP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSP {
            get {
                return this.SSPField;
            }
            set {
                if ((object.ReferenceEquals(this.SSPField, value) != true)) {
                    this.SSPField = value;
                    this.RaisePropertyChanged("SSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STA {
            get {
                return this.STAField;
            }
            set {
                if ((object.ReferenceEquals(this.STAField, value) != true)) {
                    this.STAField = value;
                    this.RaisePropertyChanged("STA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STT {
            get {
                return this.STTField;
            }
            set {
                if ((object.ReferenceEquals(this.STTField, value) != true)) {
                    this.STTField = value;
                    this.RaisePropertyChanged("STT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWT {
            get {
                return this.SWTField;
            }
            set {
                if ((object.ReferenceEquals(this.SWTField, value) != true)) {
                    this.SWTField = value;
                    this.RaisePropertyChanged("SWT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCT {
            get {
                return this.TCTField;
            }
            set {
                if ((object.ReferenceEquals(this.TCTField, value) != true)) {
                    this.TCTField = value;
                    this.RaisePropertyChanged("TCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDI {
            get {
                return this.TDIField;
            }
            set {
                if ((object.ReferenceEquals(this.TDIField, value) != true)) {
                    this.TDIField = value;
                    this.RaisePropertyChanged("TDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDR {
            get {
                return this.TDRField;
            }
            set {
                if ((object.ReferenceEquals(this.TDRField, value) != true)) {
                    this.TDRField = value;
                    this.RaisePropertyChanged("TDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDS {
            get {
                return this.TDSField;
            }
            set {
                if ((object.ReferenceEquals(this.TDSField, value) != true)) {
                    this.TDSField = value;
                    this.RaisePropertyChanged("TDS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TLR {
            get {
                return this.TLRField;
            }
            set {
                if ((object.ReferenceEquals(this.TLRField, value) != true)) {
                    this.TLRField = value;
                    this.RaisePropertyChanged("TLR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TPT {
            get {
                return this.TPTField;
            }
            set {
                if ((object.ReferenceEquals(this.TPTField, value) != true)) {
                    this.TPTField = value;
                    this.RaisePropertyChanged("TPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TSC {
            get {
                return this.TSCField;
            }
            set {
                if ((object.ReferenceEquals(this.TSCField, value) != true)) {
                    this.TSCField = value;
                    this.RaisePropertyChanged("TSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TSC_TIME {
            get {
                return this.TSC_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.TSC_TIMEField, value) != true)) {
                    this.TSC_TIMEField = value;
                    this.RaisePropertyChanged("TSC_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TSE {
            get {
                return this.TSEField;
            }
            set {
                if ((object.ReferenceEquals(this.TSEField, value) != true)) {
                    this.TSEField = value;
                    this.RaisePropertyChanged("TSE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TSE_TIME {
            get {
                return this.TSE_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.TSE_TIMEField, value) != true)) {
                    this.TSE_TIMEField = value;
                    this.RaisePropertyChanged("TSE_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TWS {
            get {
                return this.TWSField;
            }
            set {
                if ((object.ReferenceEquals(this.TWSField, value) != true)) {
                    this.TWSField = value;
                    this.RaisePropertyChanged("TWS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagSetId {
            get {
                return this.TagSetIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TagSetIdField, value) != true)) {
                    this.TagSetIdField = value;
                    this.RaisePropertyChanged("TagSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WCD {
            get {
                return this.WCDField;
            }
            set {
                if ((object.ReferenceEquals(this.WCDField, value) != true)) {
                    this.WCDField = value;
                    this.RaisePropertyChanged("WCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WDT {
            get {
                return this.WDTField;
            }
            set {
                if ((object.ReferenceEquals(this.WDTField, value) != true)) {
                    this.WDTField = value;
                    this.RaisePropertyChanged("WDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WID {
            get {
                return this.WIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WIDField, value) != true)) {
                    this.WIDField = value;
                    this.RaisePropertyChanged("WID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSM {
            get {
                return this.WSMField;
            }
            set {
                if ((object.ReferenceEquals(this.WSMField, value) != true)) {
                    this.WSMField = value;
                    this.RaisePropertyChanged("WSM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WST {
            get {
                return this.WSTField;
            }
            set {
                if ((object.ReferenceEquals(this.WSTField, value) != true)) {
                    this.WSTField = value;
                    this.RaisePropertyChanged("WST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WTI {
            get {
                return this.WTIField;
            }
            set {
                if ((object.ReferenceEquals(this.WTIField, value) != true)) {
                    this.WTIField = value;
                    this.RaisePropertyChanged("WTI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WTP {
            get {
                return this.WTPField;
            }
            set {
                if ((object.ReferenceEquals(this.WTPField, value) != true)) {
                    this.WTPField = value;
                    this.RaisePropertyChanged("WTP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCMCommitStatusProduction", Namespace="http://schemas.datacontract.org/2004/07/Mes.WcfCommonService")]
    [System.SerializableAttribute()]
    public partial class TCMCommitStatusProduction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IRFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QCBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QCGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QPSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QPTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkSequenceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDL {
            get {
                return this.IDLField;
            }
            set {
                if ((object.ReferenceEquals(this.IDLField, value) != true)) {
                    this.IDLField = value;
                    this.RaisePropertyChanged("IDL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPN {
            get {
                return this.IPNField;
            }
            set {
                if ((object.ReferenceEquals(this.IPNField, value) != true)) {
                    this.IPNField = value;
                    this.RaisePropertyChanged("IPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPT {
            get {
                return this.IPTField;
            }
            set {
                if ((object.ReferenceEquals(this.IPTField, value) != true)) {
                    this.IPTField = value;
                    this.RaisePropertyChanged("IPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IRF {
            get {
                return this.IRFField;
            }
            set {
                if ((object.ReferenceEquals(this.IRFField, value) != true)) {
                    this.IRFField = value;
                    this.RaisePropertyChanged("IRF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCD {
            get {
                return this.PCDField;
            }
            set {
                if ((object.ReferenceEquals(this.PCDField, value) != true)) {
                    this.PCDField = value;
                    this.RaisePropertyChanged("PCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PNM {
            get {
                return this.PNMField;
            }
            set {
                if ((object.ReferenceEquals(this.PNMField, value) != true)) {
                    this.PNMField = value;
                    this.RaisePropertyChanged("PNM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTI {
            get {
                return this.PTIField;
            }
            set {
                if ((object.ReferenceEquals(this.PTIField, value) != true)) {
                    this.PTIField = value;
                    this.RaisePropertyChanged("PTI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QCB {
            get {
                return this.QCBField;
            }
            set {
                if ((object.ReferenceEquals(this.QCBField, value) != true)) {
                    this.QCBField = value;
                    this.RaisePropertyChanged("QCB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QCG {
            get {
                return this.QCGField;
            }
            set {
                if ((object.ReferenceEquals(this.QCGField, value) != true)) {
                    this.QCGField = value;
                    this.RaisePropertyChanged("QCG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QCN {
            get {
                return this.QCNField;
            }
            set {
                if ((object.ReferenceEquals(this.QCNField, value) != true)) {
                    this.QCNField = value;
                    this.RaisePropertyChanged("QCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QCS {
            get {
                return this.QCSField;
            }
            set {
                if ((object.ReferenceEquals(this.QCSField, value) != true)) {
                    this.QCSField = value;
                    this.RaisePropertyChanged("QCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QCT {
            get {
                return this.QCTField;
            }
            set {
                if ((object.ReferenceEquals(this.QCTField, value) != true)) {
                    this.QCTField = value;
                    this.RaisePropertyChanged("QCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QPC {
            get {
                return this.QPCField;
            }
            set {
                if ((object.ReferenceEquals(this.QPCField, value) != true)) {
                    this.QPCField = value;
                    this.RaisePropertyChanged("QPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QPN {
            get {
                return this.QPNField;
            }
            set {
                if ((object.ReferenceEquals(this.QPNField, value) != true)) {
                    this.QPNField = value;
                    this.RaisePropertyChanged("QPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QPS {
            get {
                return this.QPSField;
            }
            set {
                if ((object.ReferenceEquals(this.QPSField, value) != true)) {
                    this.QPSField = value;
                    this.RaisePropertyChanged("QPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QPT {
            get {
                return this.QPTField;
            }
            set {
                if ((object.ReferenceEquals(this.QPTField, value) != true)) {
                    this.QPTField = value;
                    this.RaisePropertyChanged("QPT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagSetId {
            get {
                return this.TagSetIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TagSetIdField, value) != true)) {
                    this.TagSetIdField = value;
                    this.RaisePropertyChanged("TagSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkSequenceNo {
            get {
                return this.WorkSequenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkSequenceNoField, value) != true)) {
                    this.WorkSequenceNoField = value;
                    this.RaisePropertyChanged("WorkSequenceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDateTime", ReplyAction="http://tempuri.org/IService/GetDateTimeResponse")]
        string GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetDateTime", ReplyAction="http://tempuri.org/IService/GetDateTimeResponse")]
        System.IAsyncResult BeginGetDateTime(System.AsyncCallback callback, object asyncState);
        
        string EndGetDateTime(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkDate", ReplyAction="http://tempuri.org/IService/GetWorkDateResponse")]
        string GetWorkDate(string value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetWorkDate", ReplyAction="http://tempuri.org/IService/GetWorkDateResponse")]
        System.IAsyncResult BeginGetWorkDate(string value, System.AsyncCallback callback, object asyncState);
        
        string EndGetWorkDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDateTimeJson", ReplyAction="http://tempuri.org/IService/GetDateTimeJsonResponse")]
        string GetDateTimeJson(string value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetDateTimeJson", ReplyAction="http://tempuri.org/IService/GetDateTimeJsonResponse")]
        System.IAsyncResult BeginGetDateTimeJson(string value, System.AsyncCallback callback, object asyncState);
        
        string EndGetDateTimeJson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCommitStatus", ReplyAction="http://tempuri.org/IService/GetCommitStatusResponse")]
        RecoWeb01.ServiceReference.TCMCommitStatus[] GetCommitStatus(string value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetCommitStatus", ReplyAction="http://tempuri.org/IService/GetCommitStatusResponse")]
        System.IAsyncResult BeginGetCommitStatus(string value, System.AsyncCallback callback, object asyncState);
        
        RecoWeb01.ServiceReference.TCMCommitStatus[] EndGetCommitStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCommitStatusJson", ReplyAction="http://tempuri.org/IService/GetCommitStatusJsonResponse")]
        string GetCommitStatusJson(string value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetCommitStatusJson", ReplyAction="http://tempuri.org/IService/GetCommitStatusJsonResponse")]
        System.IAsyncResult BeginGetCommitStatusJson(string value, System.AsyncCallback callback, object asyncState);
        
        string EndGetCommitStatusJson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCommitStatusProduction", ReplyAction="http://tempuri.org/IService/GetCommitStatusProductionResponse")]
        RecoWeb01.ServiceReference.TCMCommitStatusProduction[] GetCommitStatusProduction(string value, string IDL);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetCommitStatusProduction", ReplyAction="http://tempuri.org/IService/GetCommitStatusProductionResponse")]
        System.IAsyncResult BeginGetCommitStatusProduction(string value, string IDL, System.AsyncCallback callback, object asyncState);
        
        RecoWeb01.ServiceReference.TCMCommitStatusProduction[] EndGetCommitStatusProduction(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCommitStatusProductionJson", ReplyAction="http://tempuri.org/IService/GetCommitStatusProductionJsonResponse")]
        string GetCommitStatusProductionJson(string value, string IDL);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetCommitStatusProductionJson", ReplyAction="http://tempuri.org/IService/GetCommitStatusProductionJsonResponse")]
        System.IAsyncResult BeginGetCommitStatusProductionJson(string value, string IDL, System.AsyncCallback callback, object asyncState);
        
        string EndGetCommitStatusProductionJson(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RecoWeb01.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDateTimeJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDateTimeJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommitStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommitStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RecoWeb01.ServiceReference.TCMCommitStatus[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RecoWeb01.ServiceReference.TCMCommitStatus[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommitStatusJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommitStatusJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommitStatusProductionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommitStatusProductionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RecoWeb01.ServiceReference.TCMCommitStatusProduction[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RecoWeb01.ServiceReference.TCMCommitStatusProduction[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommitStatusProductionJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommitStatusProductionJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RecoWeb01.ServiceReference.IService>, RecoWeb01.ServiceReference.IService {
        
        private BeginOperationDelegate onBeginGetDateTimeDelegate;
        
        private EndOperationDelegate onEndGetDateTimeDelegate;
        
        private System.Threading.SendOrPostCallback onGetDateTimeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkDateDelegate;
        
        private EndOperationDelegate onEndGetWorkDateDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkDateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDateTimeJsonDelegate;
        
        private EndOperationDelegate onEndGetDateTimeJsonDelegate;
        
        private System.Threading.SendOrPostCallback onGetDateTimeJsonCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommitStatusDelegate;
        
        private EndOperationDelegate onEndGetCommitStatusDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommitStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommitStatusJsonDelegate;
        
        private EndOperationDelegate onEndGetCommitStatusJsonDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommitStatusJsonCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommitStatusProductionDelegate;
        
        private EndOperationDelegate onEndGetCommitStatusProductionDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommitStatusProductionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommitStatusProductionJsonDelegate;
        
        private EndOperationDelegate onEndGetCommitStatusProductionJsonDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommitStatusProductionJsonCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDateTimeCompletedEventArgs> GetDateTimeCompleted;
        
        public event System.EventHandler<GetWorkDateCompletedEventArgs> GetWorkDateCompleted;
        
        public event System.EventHandler<GetDateTimeJsonCompletedEventArgs> GetDateTimeJsonCompleted;
        
        public event System.EventHandler<GetCommitStatusCompletedEventArgs> GetCommitStatusCompleted;
        
        public event System.EventHandler<GetCommitStatusJsonCompletedEventArgs> GetCommitStatusJsonCompleted;
        
        public event System.EventHandler<GetCommitStatusProductionCompletedEventArgs> GetCommitStatusProductionCompleted;
        
        public event System.EventHandler<GetCommitStatusProductionJsonCompletedEventArgs> GetCommitStatusProductionJsonCompleted;
        
        public string GetDateTime() {
            return base.Channel.GetDateTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDateTime(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDateTime(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetDateTime(System.IAsyncResult result) {
            return base.Channel.EndGetDateTime(result);
        }
        
        private System.IAsyncResult OnBeginGetDateTime(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetDateTime(callback, asyncState);
        }
        
        private object[] OnEndGetDateTime(System.IAsyncResult result) {
            string retVal = this.EndGetDateTime(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDateTimeCompleted(object state) {
            if ((this.GetDateTimeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDateTimeCompleted(this, new GetDateTimeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDateTimeAsync() {
            this.GetDateTimeAsync(null);
        }
        
        public void GetDateTimeAsync(object userState) {
            if ((this.onBeginGetDateTimeDelegate == null)) {
                this.onBeginGetDateTimeDelegate = new BeginOperationDelegate(this.OnBeginGetDateTime);
            }
            if ((this.onEndGetDateTimeDelegate == null)) {
                this.onEndGetDateTimeDelegate = new EndOperationDelegate(this.OnEndGetDateTime);
            }
            if ((this.onGetDateTimeCompletedDelegate == null)) {
                this.onGetDateTimeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDateTimeCompleted);
            }
            base.InvokeAsync(this.onBeginGetDateTimeDelegate, null, this.onEndGetDateTimeDelegate, this.onGetDateTimeCompletedDelegate, userState);
        }
        
        public string GetWorkDate(string value) {
            return base.Channel.GetWorkDate(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWorkDate(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkDate(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetWorkDate(System.IAsyncResult result) {
            return base.Channel.EndGetWorkDate(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return this.BeginGetWorkDate(value, callback, asyncState);
        }
        
        private object[] OnEndGetWorkDate(System.IAsyncResult result) {
            string retVal = this.EndGetWorkDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkDateCompleted(object state) {
            if ((this.GetWorkDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkDateCompleted(this, new GetWorkDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkDateAsync(string value) {
            this.GetWorkDateAsync(value, null);
        }
        
        public void GetWorkDateAsync(string value, object userState) {
            if ((this.onBeginGetWorkDateDelegate == null)) {
                this.onBeginGetWorkDateDelegate = new BeginOperationDelegate(this.OnBeginGetWorkDate);
            }
            if ((this.onEndGetWorkDateDelegate == null)) {
                this.onEndGetWorkDateDelegate = new EndOperationDelegate(this.OnEndGetWorkDate);
            }
            if ((this.onGetWorkDateCompletedDelegate == null)) {
                this.onGetWorkDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkDateCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkDateDelegate, new object[] {
                        value}, this.onEndGetWorkDateDelegate, this.onGetWorkDateCompletedDelegate, userState);
        }
        
        public string GetDateTimeJson(string value) {
            return base.Channel.GetDateTimeJson(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDateTimeJson(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDateTimeJson(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetDateTimeJson(System.IAsyncResult result) {
            return base.Channel.EndGetDateTimeJson(result);
        }
        
        private System.IAsyncResult OnBeginGetDateTimeJson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return this.BeginGetDateTimeJson(value, callback, asyncState);
        }
        
        private object[] OnEndGetDateTimeJson(System.IAsyncResult result) {
            string retVal = this.EndGetDateTimeJson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDateTimeJsonCompleted(object state) {
            if ((this.GetDateTimeJsonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDateTimeJsonCompleted(this, new GetDateTimeJsonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDateTimeJsonAsync(string value) {
            this.GetDateTimeJsonAsync(value, null);
        }
        
        public void GetDateTimeJsonAsync(string value, object userState) {
            if ((this.onBeginGetDateTimeJsonDelegate == null)) {
                this.onBeginGetDateTimeJsonDelegate = new BeginOperationDelegate(this.OnBeginGetDateTimeJson);
            }
            if ((this.onEndGetDateTimeJsonDelegate == null)) {
                this.onEndGetDateTimeJsonDelegate = new EndOperationDelegate(this.OnEndGetDateTimeJson);
            }
            if ((this.onGetDateTimeJsonCompletedDelegate == null)) {
                this.onGetDateTimeJsonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDateTimeJsonCompleted);
            }
            base.InvokeAsync(this.onBeginGetDateTimeJsonDelegate, new object[] {
                        value}, this.onEndGetDateTimeJsonDelegate, this.onGetDateTimeJsonCompletedDelegate, userState);
        }
        
        public RecoWeb01.ServiceReference.TCMCommitStatus[] GetCommitStatus(string value) {
            return base.Channel.GetCommitStatus(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCommitStatus(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommitStatus(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RecoWeb01.ServiceReference.TCMCommitStatus[] EndGetCommitStatus(System.IAsyncResult result) {
            return base.Channel.EndGetCommitStatus(result);
        }
        
        private System.IAsyncResult OnBeginGetCommitStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return this.BeginGetCommitStatus(value, callback, asyncState);
        }
        
        private object[] OnEndGetCommitStatus(System.IAsyncResult result) {
            RecoWeb01.ServiceReference.TCMCommitStatus[] retVal = this.EndGetCommitStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommitStatusCompleted(object state) {
            if ((this.GetCommitStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommitStatusCompleted(this, new GetCommitStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommitStatusAsync(string value) {
            this.GetCommitStatusAsync(value, null);
        }
        
        public void GetCommitStatusAsync(string value, object userState) {
            if ((this.onBeginGetCommitStatusDelegate == null)) {
                this.onBeginGetCommitStatusDelegate = new BeginOperationDelegate(this.OnBeginGetCommitStatus);
            }
            if ((this.onEndGetCommitStatusDelegate == null)) {
                this.onEndGetCommitStatusDelegate = new EndOperationDelegate(this.OnEndGetCommitStatus);
            }
            if ((this.onGetCommitStatusCompletedDelegate == null)) {
                this.onGetCommitStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommitStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommitStatusDelegate, new object[] {
                        value}, this.onEndGetCommitStatusDelegate, this.onGetCommitStatusCompletedDelegate, userState);
        }
        
        public string GetCommitStatusJson(string value) {
            return base.Channel.GetCommitStatusJson(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCommitStatusJson(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommitStatusJson(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetCommitStatusJson(System.IAsyncResult result) {
            return base.Channel.EndGetCommitStatusJson(result);
        }
        
        private System.IAsyncResult OnBeginGetCommitStatusJson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return this.BeginGetCommitStatusJson(value, callback, asyncState);
        }
        
        private object[] OnEndGetCommitStatusJson(System.IAsyncResult result) {
            string retVal = this.EndGetCommitStatusJson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommitStatusJsonCompleted(object state) {
            if ((this.GetCommitStatusJsonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommitStatusJsonCompleted(this, new GetCommitStatusJsonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommitStatusJsonAsync(string value) {
            this.GetCommitStatusJsonAsync(value, null);
        }
        
        public void GetCommitStatusJsonAsync(string value, object userState) {
            if ((this.onBeginGetCommitStatusJsonDelegate == null)) {
                this.onBeginGetCommitStatusJsonDelegate = new BeginOperationDelegate(this.OnBeginGetCommitStatusJson);
            }
            if ((this.onEndGetCommitStatusJsonDelegate == null)) {
                this.onEndGetCommitStatusJsonDelegate = new EndOperationDelegate(this.OnEndGetCommitStatusJson);
            }
            if ((this.onGetCommitStatusJsonCompletedDelegate == null)) {
                this.onGetCommitStatusJsonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommitStatusJsonCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommitStatusJsonDelegate, new object[] {
                        value}, this.onEndGetCommitStatusJsonDelegate, this.onGetCommitStatusJsonCompletedDelegate, userState);
        }
        
        public RecoWeb01.ServiceReference.TCMCommitStatusProduction[] GetCommitStatusProduction(string value, string IDL) {
            return base.Channel.GetCommitStatusProduction(value, IDL);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCommitStatusProduction(string value, string IDL, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommitStatusProduction(value, IDL, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RecoWeb01.ServiceReference.TCMCommitStatusProduction[] EndGetCommitStatusProduction(System.IAsyncResult result) {
            return base.Channel.EndGetCommitStatusProduction(result);
        }
        
        private System.IAsyncResult OnBeginGetCommitStatusProduction(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            string IDL = ((string)(inValues[1]));
            return this.BeginGetCommitStatusProduction(value, IDL, callback, asyncState);
        }
        
        private object[] OnEndGetCommitStatusProduction(System.IAsyncResult result) {
            RecoWeb01.ServiceReference.TCMCommitStatusProduction[] retVal = this.EndGetCommitStatusProduction(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommitStatusProductionCompleted(object state) {
            if ((this.GetCommitStatusProductionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommitStatusProductionCompleted(this, new GetCommitStatusProductionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommitStatusProductionAsync(string value, string IDL) {
            this.GetCommitStatusProductionAsync(value, IDL, null);
        }
        
        public void GetCommitStatusProductionAsync(string value, string IDL, object userState) {
            if ((this.onBeginGetCommitStatusProductionDelegate == null)) {
                this.onBeginGetCommitStatusProductionDelegate = new BeginOperationDelegate(this.OnBeginGetCommitStatusProduction);
            }
            if ((this.onEndGetCommitStatusProductionDelegate == null)) {
                this.onEndGetCommitStatusProductionDelegate = new EndOperationDelegate(this.OnEndGetCommitStatusProduction);
            }
            if ((this.onGetCommitStatusProductionCompletedDelegate == null)) {
                this.onGetCommitStatusProductionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommitStatusProductionCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommitStatusProductionDelegate, new object[] {
                        value,
                        IDL}, this.onEndGetCommitStatusProductionDelegate, this.onGetCommitStatusProductionCompletedDelegate, userState);
        }
        
        public string GetCommitStatusProductionJson(string value, string IDL) {
            return base.Channel.GetCommitStatusProductionJson(value, IDL);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCommitStatusProductionJson(string value, string IDL, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommitStatusProductionJson(value, IDL, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetCommitStatusProductionJson(System.IAsyncResult result) {
            return base.Channel.EndGetCommitStatusProductionJson(result);
        }
        
        private System.IAsyncResult OnBeginGetCommitStatusProductionJson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            string IDL = ((string)(inValues[1]));
            return this.BeginGetCommitStatusProductionJson(value, IDL, callback, asyncState);
        }
        
        private object[] OnEndGetCommitStatusProductionJson(System.IAsyncResult result) {
            string retVal = this.EndGetCommitStatusProductionJson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommitStatusProductionJsonCompleted(object state) {
            if ((this.GetCommitStatusProductionJsonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommitStatusProductionJsonCompleted(this, new GetCommitStatusProductionJsonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommitStatusProductionJsonAsync(string value, string IDL) {
            this.GetCommitStatusProductionJsonAsync(value, IDL, null);
        }
        
        public void GetCommitStatusProductionJsonAsync(string value, string IDL, object userState) {
            if ((this.onBeginGetCommitStatusProductionJsonDelegate == null)) {
                this.onBeginGetCommitStatusProductionJsonDelegate = new BeginOperationDelegate(this.OnBeginGetCommitStatusProductionJson);
            }
            if ((this.onEndGetCommitStatusProductionJsonDelegate == null)) {
                this.onEndGetCommitStatusProductionJsonDelegate = new EndOperationDelegate(this.OnEndGetCommitStatusProductionJson);
            }
            if ((this.onGetCommitStatusProductionJsonCompletedDelegate == null)) {
                this.onGetCommitStatusProductionJsonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommitStatusProductionJsonCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommitStatusProductionJsonDelegate, new object[] {
                        value,
                        IDL}, this.onEndGetCommitStatusProductionJsonDelegate, this.onGetCommitStatusProductionJsonCompletedDelegate, userState);
        }
    }
}
